# Generated by Django 3.1.2 on 2020-11-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_sementicrecord'),
        ('keyword_', '0002_auto_20201016_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='registrator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
            preserve_default=False,
        ),
    ]
