# Generated by Django 3.1.2 on 2020-11-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_', '0003_keyword_registrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='recent_used_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
