# Generated by Django 3.1.2 on 2020-11-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_', '0004_auto_20201110_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='recent_used_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
