# Generated by Django 3.1.2 on 2020-11-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_', '0005_auto_20201110_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='recent_used_date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
