# Generated by Django 3.1.2 on 2020-11-22 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_', '0006_auto_20201110_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='suggest_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='recent_used_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='suggest_amount',
            field=models.IntegerField(default=0),
        ),
    ]
