# Generated by Django 3.1.1 on 2020-10-16 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0003_sementicrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_time', models.DateTimeField(auto_now_add=True)),
                ('request_url', models.CharField(max_length=20)),
                ('request_method', models.CharField(max_length=10)),
                ('response_code', models.IntegerField()),
                ('keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
