# Generated by Django 3.1.1 on 2020-10-16 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_auto_20201016_0709'),
        ('keyword_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=3000)),
                ('like', models.IntegerField(default=0)),
                ('tag', models.CharField(max_length=100)),
                ('writing_date', models.DateTimeField(auto_now_add=True)),
                ('edting_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blinded', models.BooleanField(default=False)),
                ('prob_p_dp', models.FloatField(default=0.0)),
                ('prob_a_da', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('prob_is_slang', models.FloatField(default=0.0)),
                ('keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keyword_.keyword')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
        migrations.CreateModel(
            name='LikeRecord',
            fields=[
                ('like_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_like', models.BooleanField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
