# Generated by Django 3.1.1 on 2020-10-16 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_', '0001_initial'),
        ('post', '0003_auto_20201016_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyword_.keyword'),
        ),
    ]
