# Generated by Django 3.1.1 on 2020-10-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201016_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='edting_date',
            new_name='editing_date',
        ),
    ]
