# Generated by Django 3.1.3 on 2020-11-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_num_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likerecord',
            name='is_like',
        ),
        migrations.AddField(
            model_name='post',
            name='num_good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='num_lookup',
            field=models.IntegerField(default=0),
        ),
    ]
