<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-11-23 02:08
=======
# Generated by Django 3.1.2 on 2020-11-22 17:52
>>>>>>> 6149a467d11de092453fac8a5ced86d6d5e38411

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201117_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
