"""
Django settings for home project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import socket
socket.getaddrinfo('localhost', 5000)

BASE_DIR = Path(__file__).resolve().parent.parent



SECRET_KEY = 'u5$ws4#yp_7-$d+y^fgos+0*8jx0#v3khe764eg5r+-dxa!he-'

DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'djh20.iptime.org', 'localhost']



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'post',
    'member',
    'keyword_',
    'reply',
    'notice',
    'report',
    'log'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'middleware.CommonFilter.BeforeFilter',
    'middleware.CommonFilter.AfterFilter',
]

ROOT_URLCONF = 'home.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'home.wsgi.application'



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



TIME_ZONE = 'Asia/Seoul'
USE_TZ = False
USE_L10N = False
DATE_FORMAT = 'Y-m-d'
DATETIME_FORMAT = 'Y-m-d H:i:s'



STATIC_URL = '/static/'


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}


SECRET_KEY='fl7540'
ALGORITHM = 'HS256'

GOOGLE_ANALYTICS = {
    'google_analytics_id': 'UA-180299470-1',
}

URLS_AUTHORITY={ # 0 비회원, 1 회원, 2 관리자
#member
 'api/member/':0,
 'api/member/password/':0,
 'api/member/login/':1,
 'api/member/change/password':1,
 'api/member/sementic/':1,
 'api/member/admin/login/':2,
 '/api/member/manage/' : 2,

#post
 '/api/post/' : 1,
 '/api/post/<int:pk>/' : 1,
 '/api/post/like/<int:pk>/' : 1,
 '/api/post/like/record/' : 1,
 '/api/post/lookup/record/' : 1,
 '/api/post/write/record/' : 1,
 '/api/post/manage/' : 2,
 '/api/post/manage/blind/' : 2,

#reply
 '/api/reply/': 1,
 '/api/reply/write/record/': 1,
 '/api/reply/manage/': 2,
 '/api/reply/manage/blind/': 2,

#report
 '/api/report/<int:pk>': 2,
 '/api/report/manage/': 2,
 '/api/report/manage/process/': 2,

#keyword
 '/api/keyword/manage/':2,

#log
 '/api/log/login/': 1,
 '/api/log/manage/': 2,
 '/api/log/manage/login/': 2,
}

BERT_SERVER = 'http://haejun.iptime.org:6000/analyzer/analysis/'

AUTHORITY={ # 0 비회원, 1 회원, 2 관리자
 '비회원' : 0,
 '회원' : 1,
 '관리자' : 2,
}

TAG_SEPERATOR='||'

KEYWORD_ALLOW_GAP = 30

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = '@gmail.com' 
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
