# Generated by Django 3.1.2 on 2020-11-08 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0006_post_num_reply'),
        ('member', '0003_sementicrecord'),
        ('reply', '0002_auto_20201016_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_text', models.TextField(max_length=300)),
                ('process_text', models.TextField(max_length=300, null=True)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('process_date', models.DateTimeField(null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.post')),
                ('process_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_writer', to='member.member')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='reply.reply')),
                ('report_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_writer', to='member.member')),
            ],
        ),
    ]
