# Generated by Django 3.1.2 on 2020-11-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_sementicrecord'),
        ('reply', '0002_auto_20201016_0809'),
        ('post', '0006_post_num_reply'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reply',
            new_name='Report',
        ),
    ]
