# Generated by Django 3.1.2 on 2020-11-09 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_sementicrecord'),
        ('post', '0006_post_num_reply'),
        ('reply', '0002_auto_20201016_0809'),
        ('report', '0002_auto_20201108_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='process_type',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.post'),
        ),
        migrations.AlterField(
            model_name='report',
            name='process_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='process_text',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='process_writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_writer', to='member.member'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='reply.reply'),
        ),
    ]
