# Generated by Django 3.1.1 on 2020-10-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=11)),
                ('nickname', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('authority', models.IntegerField()),
                ('phonenumber', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='MemberInfo',
        ),
    ]
