# Generated by Django 3.1.1 on 2020-10-16 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20201016_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='SementicRecord',
            fields=[
                ('sementic_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
