# Generated by Django 3.1.3 on 2020-11-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_sementicrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sementicrecord',
            old_name='member_id',
            new_name='member',
        ),
        migrations.AddField(
            model_name='sementicrecord',
            name='current_temperature',
            field=models.FloatField(default=36.5),
        ),
        migrations.AddField(
            model_name='sementicrecord',
            name='initial_value',
            field=models.FloatField(default=36.5),
        ),
        migrations.AddField(
            model_name='sementicrecord',
            name='reflected_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='pw',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='sementicrecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
