# Generated by Django 3.1.1 on 2020-10-16 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0002_auto_20201016_0752'),
        ('member', '0003_sementicrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=100)),
                ('writing_date', models.DateTimeField(auto_now_add=True)),
                ('edting_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_blinded', models.BooleanField(default=False)),
                ('prob_is_slang', models.FloatField(default=0.0)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
