<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-11-15 21:13
=======
# Generated by Django 3.1.2 on 2020-11-16 21:35
>>>>>>> bfc330b7fbd7ce3a0f760162c62ea6c186e673b6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='source_url',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
